// Bundles the server and CLI into self-contained files in dist/, so the
// plugin runs straight from a git clone with no `npm install`.
import { build } from "esbuild";

await build({
	entryPoints: { server: "src/server.ts", cli: "src/cli.ts" },
	outdir: "dist",
	bundle: true,
	platform: "node",
	target: "node20",
	format: "esm",
	minify: false,
	legalComments: "none",
	banner: { js: "// Generated by build.mjs — edit src/ instead.\nimport { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
});
console.log("built dist/server.js, dist/cli.js");
